version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run: 
          name: test
          command: npm test
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: ./coverage/lcov.info
          prefix: coverage-report
